services:
  dragonify:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONNECT_ALL: false
      LOG_LEVEL: debug
    restart: always
    # dragonify needs to run as root for npm initalization
    user: '0:0'
    network_mode: none
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro